name: Sync to Hugging Face Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from the Actions tab

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetches the entire commit history

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"  # Match your local Python version

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev libomp-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==2.2.0  # Explicitly install PyTorch
          pip install numpy==1.26.4
          pip install -r requirements.txt

      - name: Verify PyTorch installation
        run: |
          python -c "import torch; print(f'PyTorch version: {torch.__version__}'); print(f'CUDA available: {torch.cuda.is_available()}')"

      - name: Debug environment
        run: |
          python --version
          pip list

      - name: Run tests
        run: |
          pytest tests/
